title: Gongshang Primary School
url: https://www.gongshangpri.moe.edu.sg
favicon: /images/gsps_favicon_2024.png
colors:
  primary-color: "#112962"
  secondary-color: "#112962"
  media-colors:
    - title: media-color-one
      color: "#002288"
    - title: media-color-two
      color: "#002288"
    - title: media-color-three
      color: "#ffcc00"
    - title: media-color-four
      color: "#e2b600"
    - title: media-color-five
      color: "#cea500"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2j3cxv28bap5s.amplifyapp.com
prod: https://master.d2j3cxv28bap5s.amplifyapp.com
shareicon: /images/logo.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: G-0EL21PSBR0
resources_name: news
